#pragma once
#include <common.h>
extern const TSpriteInterlaced weapon_slash_large_0_0;
extern const TSpriteInterlaced weapon_slash_large_0_1;
extern const TSpriteInterlaced weapon_slash_large_0_2;
extern const TSpriteInterlaced weapon_slash_large_0_3;
extern const TSpriteInterlaced weapon_slash_large_1_0;
extern const TSpriteInterlaced weapon_slash_large_1_3;
extern const TSpriteInterlaced weapon_slash_large_2_0;
extern const TSpriteInterlaced weapon_slash_large_2_3;
extern const TSpriteInterlaced weapon_slash_large_3_0;
extern const TSpriteInterlaced weapon_slash_large_3_1;
extern const TSpriteInterlaced weapon_slash_large_3_2;
extern const TSpriteInterlaced weapon_slash_large_3_3;
