#pragma once
#include "common.h"

#define TT(english,spanish) (state.language==E_ENGLISH?english:spanish)

#define T_HOUSE12 TT("THERE IS A\nLARGE TUNNEL", "HAY UN TUNNEL\nLARGO!")
#define T_HOUSE13 TT("THERE IS A\nLARGE TUNNEL", "HAY UN TUNNEL\nLARGO!")
#define T_HOUSE14 TT("THERE IS A\nLARGE TUNNEL", "HAY UN TUNNEL\nLARGO!")

#define T_HOUSE21 TT("THERE IS A\nLARGE TUNNEL", "HAY UN TUNNEL\nLARGO!")
#define T_HOUSE23 TT("THERE IS A\nLARGE TUNNEL", "HAY UN TUNNEL\nLARGO!")
#define T_HOUSE24 TT("THERE IS A\nLARGE TUNNEL", "HAY UN TUNNEL\nLARGO!")

#define T_HOUSE31 TT("THERE IS A\nLARGE TUNNEL", "HAY UN TUNNEL\nLARGO!")
#define T_HOUSE32 TT("THERE IS A\nLARGE TUNNEL", "HAY UN TUNNEL\nLARGO!")
#define T_HOUSE34 TT("THERE IS A\nLARGE TUNNEL", "HAY UN TUNNEL\nLARGO!")

#define T_HOUSE41 TT("THERE IS A\nLARGE TUNNEL", "HAY UN TUNNEL\nLARGO!")
#define T_HOUSE42 TT("THERE IS A\nLARGE TUNNEL", "HAY UN TUNNEL\nLARGO!")
#define T_HOUSE43 TT("THERE IS A\nLARGE TUNNEL", "HAY UN TUNNEL\nLARGO!")
